services:
  admin:
    image: talen2004/flec-admin:latest
    container_name: flec_admin
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:8080/api/v1
    ports:
      - "3000:80"
